name: audio_player_liontude
version: 1.0.0+1
publish_to: none
description: A Simple Audio Player for Liontude.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  audioplayers: ^0.19.1
  audio_service: ^0.17.1
  grouped_list: ^4.0.0
  http: ^0.13.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/audios/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf

